### ISSUE TITLE
Automate checks for upstream changes

### ISSUE THREAD

**Issue by stevegrunwell** [assertwell/wp-core-test-framework#1]
It would be great if we were periodically (once a week, or so) checking the upstream script file to see if anything's changed.

This would be a great opportunity to explore GitHub Actions, and I have the basic logic started:

```yaml
name: Check for out-of-date shell scripts

on:
  # Run this every Monday at 00:00:00.
  schedule:
  - cron: "0 0 0 0 1"

jobs:
  check-dependencies:
    steps:
      - name: Refresh bin/install-wp-tests.sh
        run: composer refresh-install-wp-tests
      - name: Verify if anything has changed
        run: git diff --exit-code
```

The last thing needed is to notify repo maintainers if changes were found so we can update + tag a new release accordingly.
